# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tyrone}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Lloyd"]
  s.date = %q{2010-03-27}
  s.default_executable = %q{tyrone}
  s.email = %q{christopher.lloyd@gmail.com}
  s.executables = ["tyrone"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "bin/tyrone",
     "lib/tyrone.rb",
     "lib/tyrone/app.rb",
     "logo.png",
     "templates/layout.haml.erb",
     "tyrone.gemspec"
  ]
  s.homepage = %q{http://github.com/chrislloyd/tyrone}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{tyrone}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{care the shit out of your ui}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0.13.0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.0"])
      s.add_runtime_dependency(%q<bundler>, [">= 0.9.0"])
    else
      s.add_dependency(%q<thor>, [">= 0.13.0"])
      s.add_dependency(%q<sinatra>, [">= 1.0"])
      s.add_dependency(%q<haml>, [">= 2.2.0"])
      s.add_dependency(%q<bundler>, [">= 0.9.0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0.13.0"])
    s.add_dependency(%q<sinatra>, [">= 1.0"])
    s.add_dependency(%q<haml>, [">= 2.2.0"])
    s.add_dependency(%q<bundler>, [">= 0.9.0"])
  end
end

